# Generated by Django 4.1.7 on 2023-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('user_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_mail_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
