# Generated by Django 4.1.7 on 2023-04-07 20:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=50)),
                ('service_tittle', models.CharField(max_length=50)),
                ('service_des', tinymce.models.HTMLField()),
            ],
        ),
    ]
